/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import app.Wallet;
import controller.SignController;
import controller.SystemController;
import java.awt.Color;
import java.awt.Frame;
import java.io.IOException;
import java.util.LinkedList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Banco;
import model.Cuenta;
import model.TipoCuenta;
import model.Usuario;

/**
 *
 * @author Alexis Chapal
 */
public class AddAccount extends javax.swing.JFrame {

    /**
     * Creates new form agregarCuenta
     */
    public AddAccount() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jcBanco11 = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        txtNumeroDeCuenta11 = new javax.swing.JTextField();
        jSeparator39 = new javax.swing.JSeparator();
        jSeparator40 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        jcTipoCuenta11 = new javax.swing.JComboBox<>();
        jSeparator41 = new javax.swing.JSeparator();
        botonFinalizar = new javax.swing.JPanel();
        jbFinalizar = new javax.swing.JLabel();

        jPanel12.setBackground(new java.awt.Color(70, 130, 180));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CUENTA BANCARIA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("BANCO");

        jcBanco11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BANCO_NACIONAL", "BANCO_POPULAR", "BANCO_SANTANDER", "BBVA", "BANCO_ITAU" }));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("NÚMERO DE CUENTA");

        txtNumeroDeCuenta11.setBorder(null);
        txtNumeroDeCuenta11.setPreferredSize(new java.awt.Dimension(1, 25));
        txtNumeroDeCuenta11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDeCuenta11ActionPerformed(evt);
            }
        });

        jSeparator39.setBackground(new java.awt.Color(70, 130, 180));
        jSeparator39.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator40.setBackground(new java.awt.Color(70, 130, 180));
        jSeparator40.setForeground(new java.awt.Color(255, 255, 255));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("TIPO DE CUENTA");

        jcTipoCuenta11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AHORRO", "CORRIENTE", "INVERSIÓN", " " }));

        jSeparator41.setBackground(new java.awt.Color(70, 130, 180));
        jSeparator41.setForeground(new java.awt.Color(255, 255, 255));

        botonFinalizar.setBackground(new java.awt.Color(255, 255, 255));

        jbFinalizar.setBackground(new java.awt.Color(255, 255, 255));
        jbFinalizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbFinalizar.setForeground(new java.awt.Color(70, 130, 180));
        jbFinalizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbFinalizar.setText("FINALIZAR ");
        jbFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbFinalizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbFinalizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbFinalizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbFinalizarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout botonFinalizarLayout = new javax.swing.GroupLayout(botonFinalizar);
        botonFinalizar.setLayout(botonFinalizarLayout);
        botonFinalizarLayout.setHorizontalGroup(
            botonFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        botonFinalizarLayout.setVerticalGroup(
            botonFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbFinalizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jcTipoCuenta11, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator39, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeroDeCuenta11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator40, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator41, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcBanco11, javax.swing.GroupLayout.Alignment.LEADING, 0, 146, Short.MAX_VALUE))
                .addGap(47, 185, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcBanco11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jSeparator39, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41)
                .addGap(5, 5, 5)
                .addComponent(txtNumeroDeCuenta11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator40, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42)
                .addGap(8, 8, 8)
                .addComponent(jcTipoCuenta11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator41, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroDeCuenta11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDeCuenta11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDeCuenta11ActionPerformed

    private void jbFinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFinalizarMouseClicked

    }//GEN-LAST:event_jbFinalizarMouseClicked

    private void jbFinalizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFinalizarMouseEntered
        botonFinalizar.setBackground(new Color(235, 236, 236));
    }//GEN-LAST:event_jbFinalizarMouseEntered

    private void jbFinalizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFinalizarMouseExited
        botonFinalizar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jbFinalizarMouseExited

    private void jbFinalizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFinalizarMousePressed
        Wallet wallet = Wallet.obtenerInstancia();
        Sistema sistema = Sistema.obtenerInstancia();
        Usuario usuario = sistema.usuarioPrueba;
        LinkedList<Cuenta> cuentasBancarias = usuario.getCuentasBancarias();
        String banco = String.valueOf(jcBanco11.getSelectedItem());
        String numeroCuenta = txtNumeroDeCuenta11.getText();
        String tipoCuenta = String.valueOf(jcTipoCuenta11.getSelectedItem());

        TipoCuenta tipo = TipoCuenta.AHORRO;

        if (tipoCuenta.equals("AHORRO")) {
            tipo = TipoCuenta.AHORRO;
        } else if (tipoCuenta.equals("CORRIENTE")) {
            tipo = TipoCuenta.CORRIENTE;
        } else if (tipoCuenta.equals("INVERSION")) {
            tipo = TipoCuenta.INVERSION;
        }

        double saldo = 0;
        int min = 1000000;
        int max = 10000000;
        Random random = new Random();
        // Generamos un número aleatorio entre min y max (incluidos)
        saldo = random.nextDouble((max - min) + 1) + min;

        Banco bancoN = Banco.BANCO_ITAU;

        int idCuenta = cuentasBancarias.size() + 1;

        if (banco.equals("BANCO_NACIONAL")) {
            bancoN = Banco.BANCO_NACIONAL;
        } else if (banco.equals("BANCO_POPULAR")) {
            bancoN = Banco.BANCO_POPULAR;
        } else if (banco.equals("BANCO_SANTANDER")) {
            bancoN = Banco.BANCO_SANTANDER;
        } else if (banco.equals("BBVA")) {
            bancoN = Banco.BBVA;
        } else if (banco.equals("BANCO_ITAU")) {
            bancoN = Banco.BANCO_ITAU;
        }

        //aqui se finaliza creando la cuenta bancaria y agregandola a la lista de cuentas del usuario
        Cuenta cuenta = new Cuenta(idCuenta, bancoN, numeroCuenta, tipo, saldo);
        cuentasBancarias.add(cuenta);
        double saldoTotal = sistema.usuarioPrueba.calcularSaldoT(cuentasBancarias);
        usuario.setSaldoTotal(saldoTotal);
        try {
            wallet.editarUsuario(usuario.getIdUsuario(), usuario);
            JOptionPane.showMessageDialog(null, "Cuenta agregada exitosamente" + "\npor favor inicia sesión nuevamente!");

            // Cerrar todas las ventanas abiertas
            for (Frame frame : Frame.getFrames()) {
                frame.dispose();
            }
            // Invocar el método main nuevamente para "reiniciar"
            String[] args = {};
            Wallet.main(args);

        } catch (IOException ex) {
            Logger.getLogger(AddAccount.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jbFinalizarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonFinalizar;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    public static javax.swing.JLabel jbFinalizar;
    private javax.swing.JComboBox<String> jcBanco11;
    private javax.swing.JComboBox<String> jcTipoCuenta11;
    private javax.swing.JTextField txtNumeroDeCuenta11;
    // End of variables declaration//GEN-END:variables
}
