/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.EnviosController;
import controller.ServiciosController;
import controller.SystemController;
import static java.awt.SystemColor.control;
import model.Transaccion;
import model.Usuario;
import persistencia.Persistencia;
import static view.Sistema.txtCorreo;

/**
 *
 * @author angel
 */
public class Servicios extends javax.swing.JFrame {

    /**
     * Creates new form Servicios
     */
    
    private static final Servicios instancia = new Servicios();
    public Usuario usuario = new Usuario();
    
    public Servicios() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public static Servicios obtenerInstancia(){
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBanner = new javax.swing.JPanel();
        pannelButtons = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonEnvios = new javax.swing.JPanel();
        jbEnvios = new javax.swing.JLabel();
        botonRetiros = new javax.swing.JPanel();
        jbRetiros = new javax.swing.JLabel();
        botonDepositos = new javax.swing.JPanel();
        jbDeposito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBanner.setBackground(new java.awt.Color(255, 255, 255));

        pannelButtons.setBackground(new java.awt.Color(70, 130, 180));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SERVICIOS");

        botonEnvios.setBackground(new java.awt.Color(0, 51, 102));

        jbEnvios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbEnvios.setForeground(new java.awt.Color(255, 255, 255));
        jbEnvios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbEnvios.setText("ENVIOS");
        jbEnvios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbEnviosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout botonEnviosLayout = new javax.swing.GroupLayout(botonEnvios);
        botonEnvios.setLayout(botonEnviosLayout);
        botonEnviosLayout.setHorizontalGroup(
            botonEnviosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbEnvios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        botonEnviosLayout.setVerticalGroup(
            botonEnviosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonEnviosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jbEnvios, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        botonRetiros.setBackground(new java.awt.Color(0, 51, 102));

        jbRetiros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbRetiros.setForeground(new java.awt.Color(255, 255, 255));
        jbRetiros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbRetiros.setText("RETIROS");

        javax.swing.GroupLayout botonRetirosLayout = new javax.swing.GroupLayout(botonRetiros);
        botonRetiros.setLayout(botonRetirosLayout);
        botonRetirosLayout.setHorizontalGroup(
            botonRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbRetiros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        botonRetirosLayout.setVerticalGroup(
            botonRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonRetirosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jbRetiros, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        botonDepositos.setBackground(new java.awt.Color(0, 51, 102));

        jbDeposito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbDeposito.setForeground(new java.awt.Color(255, 255, 255));
        jbDeposito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbDeposito.setText("DEPOSITOS");

        javax.swing.GroupLayout botonDepositosLayout = new javax.swing.GroupLayout(botonDepositos);
        botonDepositos.setLayout(botonDepositosLayout);
        botonDepositosLayout.setHorizontalGroup(
            botonDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbDeposito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        botonDepositosLayout.setVerticalGroup(
            botonDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonDepositosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jbDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pannelButtonsLayout = new javax.swing.GroupLayout(pannelButtons);
        pannelButtons.setLayout(pannelButtonsLayout);
        pannelButtonsLayout.setHorizontalGroup(
            pannelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelButtonsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pannelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonDepositos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRetiros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEnvios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addGroup(pannelButtonsLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel1)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        pannelButtonsLayout.setVerticalGroup(
            pannelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelButtonsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(botonEnvios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(botonRetiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(botonDepositos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBannerLayout = new javax.swing.GroupLayout(panelBanner);
        panelBanner.setLayout(panelBannerLayout);
        panelBannerLayout.setHorizontalGroup(
            panelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBannerLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(pannelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        panelBannerLayout.setVerticalGroup(
            panelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pannelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panelBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEnviosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEnviosMouseClicked
        
       ServiciosController controlador = ServiciosController.obtenerInstancia();
       controlador.setearDatos(usuario);
        
        
        
       
        
        
                
        
    }//GEN-LAST:event_jbEnviosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonDepositos;
    private javax.swing.JPanel botonEnvios;
    private javax.swing.JPanel botonRetiros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jbDeposito;
    private javax.swing.JLabel jbEnvios;
    private javax.swing.JLabel jbRetiros;
    private javax.swing.JPanel panelBanner;
    private javax.swing.JPanel pannelButtons;
    // End of variables declaration//GEN-END:variables

}
