/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import app.Wallet;
import controller.SystemController;
import java.awt.Color;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Cuenta;
import model.TipoTransaccion;
import model.Transaccion;
import model.Usuario;
import persistencia.Persistencia;

/**
 *
 * @author Alexis Chapal
 */
public class Sistema extends javax.swing.JFrame {

    /**
     * Creates new form Sistema
     */
    //aplico el patrón singleton al constructor para obtener siempre la misma instancia
    private static final Sistema instancia = new Sistema();
    public Wallet wallet = Wallet.obtenerInstancia();
    public static String nombreUsuario = "";
    public static String correoUsuario = "";
    public Usuario usuarioPrueba = new Usuario();

    private Sistema() {
        initComponents();
        tabbedSystem.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() {
            @Override
            protected int calculateTabAreaHeight(int tabPlacement, int runCount, int maxTabHeight) {
                return 0; // Ocultar la cabecera de las pestañas
            }
        });
        this.setLocationRelativeTo(null);
    }

    public static Sistema obtenerInstancia() {
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelButtons = new javax.swing.JPanel();
        botonServicios = new javax.swing.JPanel();
        jbServicios = new javax.swing.JLabel();
        botonInicio = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JLabel();
        botonCuenta = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        botonMovimientos = new javax.swing.JPanel();
        jbBotonMovimientos = new javax.swing.JLabel();
        panelBanner = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panelSystem = new javax.swing.JPanel();
        tabbedSystem = new javax.swing.JTabbedPane();
        panelHome = new javax.swing.JPanel();
        jbNombreUsuario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbSaldoDisponible = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        panelServicios = new javax.swing.JPanel();
        jcCuentasBancarias = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtNumeroCuenta = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        txtSaldoCuenta = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        txtBanco = new javax.swing.JTextField();
        txtTipoCuenta = new javax.swing.JTextField();
        botonRetiros = new javax.swing.JPanel();
        btnRetiros = new javax.swing.JLabel();
        botonDepositos = new javax.swing.JPanel();
        jbDepositos = new javax.swing.JLabel();
        botonEnvios = new javax.swing.JPanel();
        jbEnvios = new javax.swing.JLabel();
        panelMovimientos = new javax.swing.JPanel();
        panelUsuario = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jbNombreNuevoDato = new javax.swing.JLabel();
        txtNuevoDato = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        botonFinalizar = new javax.swing.JPanel();
        jbFinalizar = new javax.swing.JLabel();
        panelEnvios = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtTipoTransaccion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        txtNumeroTransaccion = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        txtCuentaOrigen = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        txtCuentaDestino = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        txtDescripcion = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        botonFinalizarDos = new javax.swing.JPanel();
        jbFinalizar1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelButtons.setBackground(new java.awt.Color(51, 51, 51));
        panelButtons.setPreferredSize(new java.awt.Dimension(1000, 600));

        botonServicios.setBackground(new java.awt.Color(0, 51, 102));

        jbServicios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbServicios.setForeground(new java.awt.Color(255, 255, 255));
        jbServicios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbServicios.setText("SERVICIOS");
        jbServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbServiciosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbServiciosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbServiciosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonServiciosLayout = new javax.swing.GroupLayout(botonServicios);
        botonServicios.setLayout(botonServiciosLayout);
        botonServiciosLayout.setHorizontalGroup(
            botonServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        botonServiciosLayout.setVerticalGroup(
            botonServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbServicios, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        botonInicio.setBackground(new java.awt.Color(0, 51, 102));

        jButtonHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonHome.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButtonHome.setText("INICIO");
        jButtonHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonHomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonInicioLayout = new javax.swing.GroupLayout(botonInicio);
        botonInicio.setLayout(botonInicioLayout);
        botonInicioLayout.setHorizontalGroup(
            botonInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        botonInicioLayout.setVerticalGroup(
            botonInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonHome, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        botonCuenta.setBackground(new java.awt.Color(0, 51, 102));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("USUARIO");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonCuentaLayout = new javax.swing.GroupLayout(botonCuenta);
        botonCuenta.setLayout(botonCuentaLayout);
        botonCuentaLayout.setHorizontalGroup(
            botonCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        botonCuentaLayout.setVerticalGroup(
            botonCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        botonMovimientos.setBackground(new java.awt.Color(0, 51, 102));

        jbBotonMovimientos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbBotonMovimientos.setForeground(new java.awt.Color(255, 255, 255));
        jbBotonMovimientos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbBotonMovimientos.setText("MOVIMIENTOS");
        jbBotonMovimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbBotonMovimientosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbBotonMovimientosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbBotonMovimientosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonMovimientosLayout = new javax.swing.GroupLayout(botonMovimientos);
        botonMovimientos.setLayout(botonMovimientosLayout);
        botonMovimientosLayout.setHorizontalGroup(
            botonMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbBotonMovimientos, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        botonMovimientosLayout.setVerticalGroup(
            botonMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbBotonMovimientos, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelButtonsLayout = new javax.swing.GroupLayout(panelButtons);
        panelButtons.setLayout(panelButtonsLayout);
        panelButtonsLayout.setHorizontalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonMovimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelButtonsLayout.setVerticalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(botonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(botonServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(botonMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(botonCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );

        getContentPane().add(panelButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 600));

        panelBanner.setBackground(new java.awt.Color(0, 51, 102));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("LA MEJOR FOKIN BILLETERA VIRTUAL DEL MUNDO");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("POR FAVOR MANEJE SU DINERO CON NOSOTROS");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("NOS LO VAMOS A ROBAR >:3");

        javax.swing.GroupLayout panelBannerLayout = new javax.swing.GroupLayout(panelBanner);
        panelBanner.setLayout(panelBannerLayout);
        panelBannerLayout.setHorizontalGroup(
            panelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBannerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBannerLayout.createSequentialGroup()
                .addGap(0, 141, Short.MAX_VALUE)
                .addGroup(panelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBannerLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBannerLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        panelBannerLayout.setVerticalGroup(
            panelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBannerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 800, 150));

        panelSystem.setBackground(new java.awt.Color(255, 255, 255));

        tabbedSystem.setBackground(new java.awt.Color(255, 255, 255));
        tabbedSystem.setToolTipText("");
        tabbedSystem.setMinimumSize(new java.awt.Dimension(800, 450));

        panelHome.setBackground(new java.awt.Color(245, 245, 245));
        panelHome.setMinimumSize(new java.awt.Dimension(800, 450));
        panelHome.setPreferredSize(new java.awt.Dimension(795, 420));

        jbNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jbNombreUsuario.setText("Damir Alexis Chapal");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("SALDO DISPONIBLE");

        jbSaldoDisponible.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbSaldoDisponible.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbSaldoDisponible.setText("$234,568,500.00");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuenta de ahorros", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(null);

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jbSaldoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel6))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSaldoDisponible)
                .addContainerGap(317, Short.MAX_VALUE))
        );

        tabbedSystem.addTab("tab1", panelHome);

        panelServicios.setBackground(new java.awt.Color(255, 255, 255));
        panelServicios.setMinimumSize(new java.awt.Dimension(800, 450));
        panelServicios.setPreferredSize(new java.awt.Dimension(795, 420));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("CUENTAS DISPONIBLES");

        jPanel2.setBackground(new java.awt.Color(70, 130, 180));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CUENTA BANCARIA ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BANCO");

        jSeparator8.setBackground(new java.awt.Color(70, 130, 180));
        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("NÚMERO DE CUENTA");

        txtNumeroCuenta.setEditable(false);
        txtNumeroCuenta.setBorder(null);
        txtNumeroCuenta.setPreferredSize(new java.awt.Dimension(1, 25));
        txtNumeroCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCuentaActionPerformed(evt);
            }
        });

        jSeparator9.setBackground(new java.awt.Color(70, 130, 180));
        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TIPO DE CUENTA");

        jSeparator10.setBackground(new java.awt.Color(70, 130, 180));
        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));

        txtSaldoCuenta.setEditable(false);
        txtSaldoCuenta.setBorder(null);
        txtSaldoCuenta.setPreferredSize(new java.awt.Dimension(1, 25));
        txtSaldoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoCuentaActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SALDO DISPONIBLE");

        jSeparator11.setBackground(new java.awt.Color(70, 130, 180));
        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));

        txtBanco.setEditable(false);
        txtBanco.setBorder(null);
        txtBanco.setPreferredSize(new java.awt.Dimension(1, 25));
        txtBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBancoActionPerformed(evt);
            }
        });

        txtTipoCuenta.setEditable(false);
        txtTipoCuenta.setBorder(null);
        txtTipoCuenta.setPreferredSize(new java.awt.Dimension(1, 25));
        txtTipoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTipoCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(txtBanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSaldoCuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(5, 5, 5)
                .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(5, 5, 5)
                .addComponent(txtSaldoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonRetiros.setBackground(new java.awt.Color(70, 130, 180));

        btnRetiros.setBackground(new java.awt.Color(70, 130, 180));
        btnRetiros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRetiros.setForeground(new java.awt.Color(255, 255, 255));
        btnRetiros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRetiros.setText("RETIROS");
        btnRetiros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetirosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRetirosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRetirosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonRetirosLayout = new javax.swing.GroupLayout(botonRetiros);
        botonRetiros.setLayout(botonRetirosLayout);
        botonRetirosLayout.setHorizontalGroup(
            botonRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRetiros, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        botonRetirosLayout.setVerticalGroup(
            botonRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRetiros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        botonDepositos.setBackground(new java.awt.Color(70, 130, 180));

        jbDepositos.setBackground(new java.awt.Color(70, 130, 180));
        jbDepositos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbDepositos.setForeground(new java.awt.Color(255, 255, 255));
        jbDepositos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbDepositos.setText("DEPOSITOS");
        jbDepositos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbDepositosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbDepositosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbDepositosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonDepositosLayout = new javax.swing.GroupLayout(botonDepositos);
        botonDepositos.setLayout(botonDepositosLayout);
        botonDepositosLayout.setHorizontalGroup(
            botonDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbDepositos, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        botonDepositosLayout.setVerticalGroup(
            botonDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbDepositos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        botonEnvios.setBackground(new java.awt.Color(70, 130, 180));

        jbEnvios.setBackground(new java.awt.Color(70, 130, 180));
        jbEnvios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbEnvios.setForeground(new java.awt.Color(255, 255, 255));
        jbEnvios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbEnvios.setText("ENVIOS");
        jbEnvios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbEnviosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbEnviosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbEnviosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonEnviosLayout = new javax.swing.GroupLayout(botonEnvios);
        botonEnvios.setLayout(botonEnviosLayout);
        botonEnviosLayout.setHorizontalGroup(
            botonEnviosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbEnvios, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        botonEnviosLayout.setVerticalGroup(
            botonEnviosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbEnvios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelServiciosLayout = new javax.swing.GroupLayout(panelServicios);
        panelServicios.setLayout(panelServiciosLayout);
        panelServiciosLayout.setHorizontalGroup(
            panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcCuentasBancarias, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelServiciosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addGroup(panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelServiciosLayout.createSequentialGroup()
                        .addComponent(botonEnvios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonRetiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(botonDepositos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96))
        );
        panelServiciosLayout.setVerticalGroup(
            panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServiciosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelServiciosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcCuentasBancarias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonRetiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEnvios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDepositos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        tabbedSystem.addTab("tab2", panelServicios);

        panelMovimientos.setBackground(new java.awt.Color(245, 245, 245));
        panelMovimientos.setMinimumSize(new java.awt.Dimension(800, 450));

        javax.swing.GroupLayout panelMovimientosLayout = new javax.swing.GroupLayout(panelMovimientos);
        panelMovimientos.setLayout(panelMovimientosLayout);
        panelMovimientosLayout.setHorizontalGroup(
            panelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        panelMovimientosLayout.setVerticalGroup(
            panelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        tabbedSystem.addTab("tab3", panelMovimientos);

        panelUsuario.setBackground(new java.awt.Color(255, 255, 255));
        panelUsuario.setMinimumSize(new java.awt.Dimension(800, 450));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("NOMBRE");

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(null);
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtNombre.setPreferredSize(new java.awt.Dimension(1, 25));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(70, 130, 180));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("CORREO ELECTRONICO");

        txtCorreo.setEditable(false);
        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setBorder(null);
        txtCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCorreo.setPreferredSize(new java.awt.Dimension(1, 25));
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(70, 130, 180));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("TELEFONO");

        txtTelefono.setEditable(false);
        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono.setBorder(null);
        txtTelefono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtTelefono.setPreferredSize(new java.awt.Dimension(1, 25));
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(70, 130, 180));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("DIRECCIÓN");

        txtDireccion.setEditable(false);
        txtDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccion.setBorder(null);
        txtDireccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDireccion.setPreferredSize(new java.awt.Dimension(1, 25));
        txtDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDireccionMousePressed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(70, 130, 180));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(70, 130, 180));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MODIFICAR DATOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator6.setBackground(new java.awt.Color(70, 130, 180));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        jbNombreNuevoDato.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbNombreNuevoDato.setForeground(new java.awt.Color(255, 255, 255));
        jbNombreNuevoDato.setText("NOMBRE\n");

        txtNuevoDato.setBorder(null);
        txtNuevoDato.setPreferredSize(new java.awt.Dimension(1, 25));
        txtNuevoDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoDatoActionPerformed(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(70, 130, 180));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));

        botonFinalizar.setBackground(new java.awt.Color(255, 255, 255));

        jbFinalizar.setBackground(new java.awt.Color(255, 255, 255));
        jbFinalizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbFinalizar.setForeground(new java.awt.Color(70, 130, 180));
        jbFinalizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbFinalizar.setText("FINALIZAR ");
        jbFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbFinalizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbFinalizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbFinalizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbFinalizarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout botonFinalizarLayout = new javax.swing.GroupLayout(botonFinalizar);
        botonFinalizar.setLayout(botonFinalizarLayout);
        botonFinalizarLayout.setHorizontalGroup(
            botonFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        botonFinalizarLayout.setVerticalGroup(
            botonFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbFinalizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNuevoDato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbNombreNuevoDato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(botonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNombreNuevoDato)
                .addGap(5, 5, 5)
                .addComponent(txtNuevoDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        tabbedSystem.addTab("tab4", panelUsuario);

        panelEnvios.setBackground(new java.awt.Color(70, 130, 180));
        panelEnvios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENVIOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        panelEnvios.setMinimumSize(new java.awt.Dimension(800, 450));
        panelEnvios.setPreferredSize(new java.awt.Dimension(780, 420));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("TIPO");

        txtTipoTransaccion.setEditable(false);
        txtTipoTransaccion.setBorder(null);
        txtTipoTransaccion.setPreferredSize(new java.awt.Dimension(1, 25));
        txtTipoTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoTransaccionActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("NÚMERO DE TRANSACCIÓN");

        jSeparator12.setBackground(new java.awt.Color(70, 130, 180));
        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));

        txtNumeroTransaccion.setEditable(false);
        txtNumeroTransaccion.setBorder(null);
        txtNumeroTransaccion.setPreferredSize(new java.awt.Dimension(1, 25));
        txtNumeroTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroTransaccionActionPerformed(evt);
            }
        });

        jSeparator13.setBackground(new java.awt.Color(70, 130, 180));
        jSeparator13.setForeground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("FECHA");

        txtFecha.setEditable(false);
        txtFecha.setBorder(null);
        txtFecha.setPreferredSize(new java.awt.Dimension(1, 25));
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        jSeparator14.setBackground(new java.awt.Color(70, 130, 180));
        jSeparator14.setForeground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("CANTIDAD");

        txtCantidad.setBorder(null);
        txtCantidad.setPreferredSize(new java.awt.Dimension(1, 25));
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        jSeparator15.setBackground(new java.awt.Color(70, 130, 180));
        jSeparator15.setForeground(new java.awt.Color(255, 255, 255));

        txtCuentaOrigen.setEditable(false);
        txtCuentaOrigen.setBorder(null);
        txtCuentaOrigen.setPreferredSize(new java.awt.Dimension(1, 25));
        txtCuentaOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentaOrigenActionPerformed(evt);
            }
        });

        jSeparator16.setBackground(new java.awt.Color(70, 130, 180));
        jSeparator16.setForeground(new java.awt.Color(255, 255, 255));

        txtCuentaDestino.setBorder(null);
        txtCuentaDestino.setPreferredSize(new java.awt.Dimension(1, 25));
        txtCuentaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentaDestinoActionPerformed(evt);
            }
        });

        jSeparator17.setBackground(new java.awt.Color(70, 130, 180));
        jSeparator17.setForeground(new java.awt.Color(255, 255, 255));

        txtDescripcion.setBorder(null);
        txtDescripcion.setPreferredSize(new java.awt.Dimension(1, 25));
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("DESCRIPCIÓN");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("CUENTA DESTINO");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("NÚMERO DE CUENTA");

        jSeparator18.setBackground(new java.awt.Color(70, 130, 180));
        jSeparator18.setForeground(new java.awt.Color(255, 255, 255));

        botonFinalizarDos.setBackground(new java.awt.Color(255, 255, 255));

        jbFinalizar1.setBackground(new java.awt.Color(255, 255, 255));
        jbFinalizar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbFinalizar1.setForeground(new java.awt.Color(70, 130, 180));
        jbFinalizar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbFinalizar1.setText("FINALIZAR ");
        jbFinalizar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbFinalizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbFinalizar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbFinalizar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbFinalizar1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbFinalizar1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout botonFinalizarDosLayout = new javax.swing.GroupLayout(botonFinalizarDos);
        botonFinalizarDos.setLayout(botonFinalizarDosLayout);
        botonFinalizarDosLayout.setHorizontalGroup(
            botonFinalizarDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbFinalizar1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        botonFinalizarDosLayout.setVerticalGroup(
            botonFinalizarDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbFinalizar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("**Por favor ingrese los datos de cuentas y cantidad a enviar sin puntos ni comas");

        javax.swing.GroupLayout panelEnviosLayout = new javax.swing.GroupLayout(panelEnvios);
        panelEnvios.setLayout(panelEnviosLayout);
        panelEnviosLayout.setHorizontalGroup(
            panelEnviosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEnviosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonFinalizarDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
            .addGroup(panelEnviosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelEnviosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(panelEnviosLayout.createSequentialGroup()
                        .addGroup(panelEnviosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTipoTransaccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroTransaccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105)
                        .addGroup(panelEnviosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCuentaOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCuentaDestino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator17, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator18, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        panelEnviosLayout.setVerticalGroup(
            panelEnviosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnviosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelEnviosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelEnviosLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTipoTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addGap(5, 5, 5)
                        .addComponent(txtNumeroTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEnviosLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCuentaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addGap(5, 5, 5)
                        .addComponent(txtCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(5, 5, 5)
                .addGroup(panelEnviosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEnviosLayout.createSequentialGroup()
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(botonFinalizarDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        tabbedSystem.addTab("tab5", panelEnvios);

        javax.swing.GroupLayout panelSystemLayout = new javax.swing.GroupLayout(panelSystem);
        panelSystem.setLayout(panelSystemLayout);
        panelSystemLayout.setHorizontalGroup(
            panelSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSystemLayout.createSequentialGroup()
                .addComponent(tabbedSystem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelSystemLayout.setVerticalGroup(
            panelSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedSystem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panelSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 800, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHomeMouseEntered

        botonInicio.setBackground(new Color(0, 54, 132));
    }//GEN-LAST:event_jButtonHomeMouseEntered

    private void jButtonHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHomeMouseExited
        botonInicio.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_jButtonHomeMouseExited

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNuevoDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoDatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoDatoActionPerformed

    private void jbFinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFinalizarMouseClicked


    }//GEN-LAST:event_jbFinalizarMouseClicked

    private void jbFinalizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFinalizarMouseEntered
        botonFinalizar.setBackground(new Color(235, 236, 236));
    }//GEN-LAST:event_jbFinalizarMouseEntered

    private void jbFinalizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFinalizarMouseExited
        botonFinalizar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jbFinalizarMouseExited

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        jbNombreNuevoDato.setText("NOMBRE");
        txtNuevoDato.setText(txtNombre.getText());
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        jbNombreNuevoDato.setText("CORREO ELECTRONICO");
        txtNuevoDato.setText(txtCorreo.getText());

    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
        jbNombreNuevoDato.setText("TELEFONO");
        txtNuevoDato.setText(txtTelefono.getText());
    }//GEN-LAST:event_txtTelefonoMousePressed

    private void txtDireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionMousePressed
        jbNombreNuevoDato.setText("DIRECCIÓN");
        txtNuevoDato.setText(txtDireccion.getText());
    }//GEN-LAST:event_txtDireccionMousePressed

    private void jbFinalizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFinalizarMousePressed
        SystemController control = SystemController.obtenerInstancia();
        Wallet wallet = Wallet.obtenerInstancia();
        Usuario usuario = wallet.obtenerUsuario(txtNombre.getText(), txtCorreo.getText());
        System.out.println("Obteniendo datos..");
        if (jbNombreNuevoDato.getText().trim().equals("NOMBRE")) {
            System.out.println("Modificando datos...");
            usuario.setNombreCompleto(txtNuevoDato.getText());
            try {
                control.editarUsuario(usuario);
                System.out.println("Datos modificados...!");
                JOptionPane.showMessageDialog(null, "DATOS MODIFICADOS CORRECTAMENTE\n INICIE SESIÓN NUEVAMENTE");
                this.dispose();
            } catch (IOException ex) {
                Logger.getLogger(Sistema.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (jbNombreNuevoDato.getText().trim().equals("CORREO ELECTRONICO")) {
            System.out.println("Modificando datos...");
            usuario.setCorreoElectronico(txtNuevoDato.getText());
            try {
                control.editarUsuario(usuario);
                System.out.println("Datos modificados...!");
                JOptionPane.showMessageDialog(null, "DATOS MODIFICADOS CORRECTAMENTE\n INICIE SESIÓN NUEVAMENTE");
                this.dispose();
            } catch (IOException ex) {
                Logger.getLogger(Sistema.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (jbNombreNuevoDato.getText().trim().equals("TELEFONO")) {
            System.out.println("Modificando datos...");
            usuario.setNumeroTelefono(txtNuevoDato.getText());
            try {
                control.editarUsuario(usuario);
                System.out.println("Datos modificados...!");
                JOptionPane.showMessageDialog(null, "DATOS MODIFICADOS CORRECTAMENTE\n INICIE SESIÓN NUEVAMENTE");
                this.dispose();
            } catch (IOException ex) {
                Logger.getLogger(Sistema.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (jbNombreNuevoDato.getText().trim().equals("DIRECCION")) {
            System.out.println("Modificando datos...");
            usuario.setDireccion(txtNuevoDato.getText());
            try {
                control.editarUsuario(usuario);
                System.out.println("Datos modificados...!");
                JOptionPane.showMessageDialog(null, "DATOS MODIFICADOS CORRECTAMENTE\n INICIE SESIÓN NUEVAMENTE");
                this.dispose();
            } catch (IOException ex) {
                Logger.getLogger(Sistema.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_jbFinalizarMousePressed

    private void jbServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbServiciosMouseClicked
        SystemController control = SystemController.obtenerInstancia();
        for (Cuenta cuentas : usuarioPrueba.getCuentasBancarias()) {
            jcCuentasBancarias.addItem(cuentas.getNumeroCuenta());
            try {
                control.usarBotonServicios(usuarioPrueba, String.valueOf(jcCuentasBancarias.getSelectedItem()));

            } catch (Exception e) {
            }

        }
        tabbedSystem.setSelectedIndex(1);

//        ServiciosController serviciosController = ServiciosController.obtenerInstancia();
//        Wallet wallet = Wallet.obtenerInstancia();
//        serviciosController.mostrarVentana(wallet.obtenerUsuario(nombreUsuario, correoUsuario));

    }//GEN-LAST:event_jbServiciosMouseClicked

    private void jButtonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHomeMouseClicked

        tabbedSystem.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonHomeMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        tabbedSystem.setSelectedIndex(3);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jbBotonMovimientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbBotonMovimientosMouseClicked
        tabbedSystem.setSelectedIndex(2);
    }//GEN-LAST:event_jbBotonMovimientosMouseClicked

    private void txtNumeroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCuentaActionPerformed

    private void txtSaldoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoCuentaActionPerformed

    private void txtBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBancoActionPerformed

    private void txtTipoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoCuentaActionPerformed

    private void btnRetirosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirosMouseClicked

    }//GEN-LAST:event_btnRetirosMouseClicked

    private void btnRetirosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirosMouseEntered
        botonRetiros.setBackground(new Color(78, 123, 160));
    }//GEN-LAST:event_btnRetirosMouseEntered

    private void btnRetirosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirosMouseExited
        botonRetiros.setBackground(new Color(70, 130, 180));
    }//GEN-LAST:event_btnRetirosMouseExited

    private void jbDepositosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbDepositosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbDepositosMouseClicked

    private void jbDepositosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbDepositosMouseEntered
        botonDepositos.setBackground(new Color(78, 123, 160));
    }//GEN-LAST:event_jbDepositosMouseEntered

    private void jbDepositosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbDepositosMouseExited
        botonDepositos.setBackground(new Color(70, 130, 180));
    }//GEN-LAST:event_jbDepositosMouseExited

    private void jbEnviosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEnviosMouseClicked
        Wallet wallet = Wallet.obtenerInstancia();
        int idTransferencia = 0;
        txtTipoTransaccion.setText("TRANSFERENCIA");
        if (wallet.listaTransacciones == null) {

            txtNumeroTransaccion.setText(String.valueOf(idTransferencia + 1));
        } else {
            txtNumeroTransaccion.setText(String.valueOf(wallet.listaTransacciones.size() + 1));
        }

        LocalDateTime fecha = LocalDateTime.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        String fechaFormateada = fecha.format(formato);
        txtFecha.setText(fechaFormateada.toString());
        txtCuentaOrigen.setText(txtNumeroCuenta.getText());

        tabbedSystem.setSelectedIndex(4);

    }//GEN-LAST:event_jbEnviosMouseClicked

    private void jbEnviosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEnviosMouseEntered
        botonEnvios.setBackground(new Color(78, 123, 160));
    }//GEN-LAST:event_jbEnviosMouseEntered

    private void jbEnviosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEnviosMouseExited
        botonEnvios.setBackground(new Color(70, 130, 180));
    }//GEN-LAST:event_jbEnviosMouseExited

    private void txtNumeroTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroTransaccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroTransaccionActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtTipoTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoTransaccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoTransaccionActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtCuentaOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentaOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentaOrigenActionPerformed

    private void txtCuentaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentaDestinoActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void jbFinalizar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFinalizar1MouseClicked
        SystemController control = SystemController.obtenerInstancia();

        double idTransaccion = Double.parseDouble(txtNumeroTransaccion.getText());
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        LocalDateTime fecha = LocalDateTime.parse(txtFecha.getText(), formato);
        double monto = Double.parseDouble(txtCantidad.getText());

        String cuentaOrigen = txtCuentaOrigen.getText();
        String cuentaDestino = txtCuentaDestino.getText();
        String descripcion = txtDescripcion.getText();

        Transaccion transaccion = new Transaccion();

        TipoTransaccion tipo = transaccion.obtenerTipoTransaccion(txtTipoTransaccion.getText());
        transaccion.setCuentaDestino(cuentaDestino);
        transaccion.setCuentaOrigen(cuentaOrigen);
        transaccion.setDescripcion(descripcion);
        transaccion.setFecha(fecha.toString());
        transaccion.setIdTransaccion(idTransaccion);
        transaccion.setMonto(monto);
        transaccion.setTipoTransaccion(tipo);
        transaccion.setIdentificador(String.valueOf(usuarioPrueba.getIdUsuario()));
        try {
            control.guardarTransaccion(transaccion);
        } catch (IOException ex) {
            Logger.getLogger(Sistema.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbFinalizar1MouseClicked

    private void jbFinalizar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFinalizar1MouseEntered
        botonFinalizarDos.setBackground(new Color(235, 236, 236));
    }//GEN-LAST:event_jbFinalizar1MouseEntered

    private void jbFinalizar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFinalizar1MouseExited
        botonFinalizarDos.setBackground(Color.WHITE);
    }//GEN-LAST:event_jbFinalizar1MouseExited

    private void jbFinalizar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFinalizar1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbFinalizar1MousePressed

    private void jbServiciosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbServiciosMouseEntered
        botonServicios.setBackground(new Color(0, 54, 132));
    }//GEN-LAST:event_jbServiciosMouseEntered

    private void jbServiciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbServiciosMouseExited
        botonServicios.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_jbServiciosMouseExited

    private void jbBotonMovimientosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbBotonMovimientosMouseEntered
        botonMovimientos.setBackground(new Color(0, 54, 132));
    }//GEN-LAST:event_jbBotonMovimientosMouseEntered

    private void jbBotonMovimientosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbBotonMovimientosMouseExited
        botonMovimientos.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_jbBotonMovimientosMouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        botonCuenta.setBackground(new Color(0, 54, 132));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        botonCuenta.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_jLabel4MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonCuenta;
    private javax.swing.JPanel botonDepositos;
    private javax.swing.JPanel botonEnvios;
    private javax.swing.JPanel botonFinalizar;
    private javax.swing.JPanel botonFinalizarDos;
    private javax.swing.JPanel botonInicio;
    private javax.swing.JPanel botonMovimientos;
    private javax.swing.JPanel botonRetiros;
    private javax.swing.JPanel botonServicios;
    private javax.swing.JLabel btnRetiros;
    private javax.swing.JLabel jButtonHome;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel jbBotonMovimientos;
    private javax.swing.JLabel jbDepositos;
    private javax.swing.JLabel jbEnvios;
    private javax.swing.JLabel jbFinalizar;
    private javax.swing.JLabel jbFinalizar1;
    public static javax.swing.JLabel jbNombreNuevoDato;
    public static javax.swing.JLabel jbNombreUsuario;
    public static javax.swing.JLabel jbSaldoDisponible;
    private javax.swing.JLabel jbServicios;
    public static javax.swing.JComboBox<String> jcCuentasBancarias;
    private javax.swing.JPanel panelBanner;
    public static javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelEnvios;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelMovimientos;
    private javax.swing.JPanel panelServicios;
    private javax.swing.JPanel panelSystem;
    private javax.swing.JPanel panelUsuario;
    public static javax.swing.JTabbedPane tabbedSystem;
    public static javax.swing.JTextField txtBanco;
    private javax.swing.JTextField txtCantidad;
    public static javax.swing.JTextField txtCorreo;
    public static javax.swing.JTextField txtCuentaDestino;
    private javax.swing.JTextField txtCuentaOrigen;
    private javax.swing.JTextField txtDescripcion;
    public static javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFecha;
    public static javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNuevoDato;
    public static javax.swing.JTextField txtNumeroCuenta;
    private javax.swing.JTextField txtNumeroTransaccion;
    public static javax.swing.JTextField txtSaldoCuenta;
    public static javax.swing.JTextField txtTelefono;
    public static javax.swing.JTextField txtTipoCuenta;
    private javax.swing.JTextField txtTipoTransaccion;
    // End of variables declaration//GEN-END:variables
}
